# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: url_shortener.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'url_shortener.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13url_shortener.proto\x12\x0curlshortener\":\n\x0eShortenRequest\x12\x14\n\x0coriginal_url\x18\x01 \x01(\t\x12\x12\n\nexpiration\x18\x02 \x01(\x05\"$\n\x0fShortenResponse\x12\x11\n\tshort_url\x18\x01 \x01(\t\"#\n\x0eResolveRequest\x12\x11\n\tshort_url\x18\x01 \x01(\t\"\'\n\x0fResolveResponse\x12\x14\n\x0coriginal_url\x18\x01 \x01(\t2\x9e\x01\n\x0cURLShortener\x12\x46\n\x07Shorten\x12\x1c.urlshortener.ShortenRequest\x1a\x1d.urlshortener.ShortenResponse\x12\x46\n\x07Resolve\x12\x1c.urlshortener.ResolveRequest\x1a\x1d.urlshortener.ResolveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'url_shortener_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHORTENREQUEST']._serialized_start=37
  _globals['_SHORTENREQUEST']._serialized_end=95
  _globals['_SHORTENRESPONSE']._serialized_start=97
  _globals['_SHORTENRESPONSE']._serialized_end=133
  _globals['_RESOLVEREQUEST']._serialized_start=135
  _globals['_RESOLVEREQUEST']._serialized_end=170
  _globals['_RESOLVERESPONSE']._serialized_start=172
  _globals['_RESOLVERESPONSE']._serialized_end=211
  _globals['_URLSHORTENER']._serialized_start=214
  _globals['_URLSHORTENER']._serialized_end=372
# @@protoc_insertion_point(module_scope)
